#!/bin/sh

# 添加防火墙允许规则
uci -q batch <<-EOF >/dev/null
	delete firewall.autoupdate

	set firewall.autoupdate=rule
	set firewall.autoupdate.name='Allow-Autoupdate'
	set firewall.autoupdate.src='wan'
	set firewall.autoupdate.target='ACCEPT'
	set firewall.autoupdate.enabled='1'
	commit firewall
EOF

exit 0
