name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev \
            gawk git gettext libssl-dev wget

      - name: Download OpenWrt SDK (for IPK)
        run: |
          # 使用稳定版本的 SDK 而不是快照版，通常稳定版默认生成 ipk
          SDK_URL="https://downloads.openwrt.org/releases/24.10.4/targets/qualcommax/ipq807x/openwrt-sdk-24.10.4-qualcommax-ipq807x_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          wget $SDK_URL
          tar -xf openwrt-sdk-*.tar.xz
          rm -rf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* openwrt-sdk

      - name: Prepare Package Source
        run: |
          mkdir -p openwrt-sdk/package/luci-app-autoupdate
          cp -r htdocs root Makefile openwrt-sdk/package/luci-app-autoupdate/

      - name: Update Feeds
        run: |
          cd openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build Package
        run: |
          cd openwrt-sdk
          echo "CONFIG_PACKAGE_luci-app-autoupdate=m" > .config
          make defconfig
          make package/luci-app-autoupdate/compile V=s

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: openwrt-sdk/bin/packages/aarch64_cortex-a53/base/luci-app-autoupdate_*.ipk
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## LuCI App Auto Update - Release ${{ github.ref_name }}
            
            ### 安装说明 / Installation
            
            下载 `.ipk` 文件，适用于 Qualcomm IPQ8071A 平台设备：
            - 支持 Qualcommax IPQ807x 系列芯片 (如 IPQ8071A)
            - ARM64 架构
            - 基于 OpenWrt 23.05.2 稳定版构建
            
            安装命令：
            ### 安装说明 / Installation
            
            下载 `.apk` 文件，适用于 Qualcomm IPQ8071A 平台设备：
            - 支持 Qualcommax IPQ807x 系列芯片 (如 IPQ8071A)
            - ARM64 架构
            - 基于最新 OpenWrt snapshots 构建
            
            安装命令：
            ```bash
            apk add --allow-untrusted luci-app-autoupdate_*.apk
            ```
            
            ### 功能特性 / Features
            - 自动固件更新
            - 支持多种下载源
            - 基于 ucode 实现
            - 现代 LuCI 界面
            
            ### 依赖要求 / Dependencies
            - wget
            - ucode
            - ucode-mod-uci
            - ucode-mod-ubus
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
